### ISSUE TITLE
引入文件后，全局设置UINavgation样式不生效

### ISSUE THREAD

**Issue by mahong125** [Draveness/DKNightVersion#10]
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    
    ViewController *view = [[ViewController alloc] init];
    UINavigationController *mainNav = [[UINavigationController alloc] initWithRootViewController:view];
    self.window.rootViewController = mainNav;
    

//这两个设置不生效，请问下是怎么回事。。。。
    [[UINavigationBar appearance] setBarTintColor:[UIColor redColor]];
    
    [[UINavigationBar appearance] setTintColor:[UIColor yellowColor]];
    
    
    
    return YES;
}

**Comment by Draveness** [comment]
You may use `self.navigationController.navigationBar.barTintColor = [UIColor redColor]` instead.
