### ISSUE TITLE
In Demo, RootViewController:'viewDidLoad' add '[self change];' ,color change error

### ISSUE THREAD

**Issue by madordie** [Draveness/DKNightVersion#11]
hi.

Demo : 

---------------------------------
- (void)viewDidLoad {
    .....
    [self change];
}
---------------------------------

is OK .

But click Change Button .

is NOT OK .

have textBackcolor is no change.and have black.......

**Comment by Draveness** [comment]
Sorry, I donot understand what you mean.

**Comment by madordie** [comment]
3Q

**Comment by madordie** [comment]
¯\_(ツ)_/¯🌹
I've solved the problem.

**Comment by Draveness** [comment]
= =
