### ISSUE TITLE
你好，针对iOS13的修改，是不是不太严谨？

### ISSUE THREAD

**Issue by ncwubird** [Draveness/DKNightVersion#117]
#if defined(__IPHONE_13_0)
        UISearchTextField *searchField = obj.searchTextField;
        searchField.keyboardAppearance = UIKeyboardAppearanceDefault;
#elif defined(__IPHONE_7_0)
        UITextField *searchField = [obj valueForKey:@"_searchField"];
        searchField.keyboardAppearance = UIKeyboardAppearanceDefault;
#else
        obj.keyboardAppearance = UIKeyboardAppearanceDefault;
#endif

我的iphone是iOS 12.4，在使用Xcode 11调试时，会出现闪退，是否应该加上下面类似的处理？
#if defined(__IPHONE_13_0)
        if (@available(iOS 13, *)) {
            UISearchTextField *searchField = obj.searchTextField;
            searchField.keyboardAppearance = UIKeyboardAppearanceDefault;
        }

**Comment by fabiosoft** [comment]
take a look here... #118
