### ISSUE TITLE
Change theme while scrolling problem

### ISSUE THREAD

**Issue by emilyZhouwm** [Draveness/DKNightVersion#15]
黑色模式下，tableview保持滚动着，点击切换白天模式，会有一个cell的label底色变成黑色
![7c2ba091-be85-4898-8ea1-92ea0599bde9](https://cloud.githubusercontent.com/assets/6175955/9282692/d47fd7d6-4300-11e5-9705-f76edb4db423.png)

**Comment by Draveness** [comment]
I have already discovered this problem. But this maybe caused by UITableView reuse mechanism. So just change theme in setting tab or some other place. If you want to use this safely, never change theme when table view scrolling until I work this out. = =

**Comment by emilyZhouwm** [comment]
在真机上似乎并没有这个问题

**Comment by DanyZhang** [comment]
In the use of your third party, we met in the program of these problems ：1.Switch to the night mode, then switch to the mode during the day, some cell appeared under control (label) on the black background, above the label data disappeared, and there will be a phenomenon of cell multiplexing？2.The import of a third party, you will is our program to change the font (black fonts into a red, red fonts become white)？ 3. Navigation around the color of the button is our custom, after the switch to the night mode, switch back, about navigation button color becomes blue, not our custom colors ？Thank you for your answer，We can add the qq chat with these questions if you have time!

**Comment by Draveness** [comment]
I think you should use the latest version for DKNightVersion @DanyZhang
