### ISSUE TITLE
If a modal is presented when changing themes, it won't change the presenting view controller's theme

### ISSUE THREAD

**Issue by jaysonlane** [Draveness/DKNightVersion#2]
If a modal view controller is presented when you change the theme, the presenting view controller and subviews will not be redrawn to display the new theme after the modal view is dismissed.

**Comment by jaysonlane** [comment]
A possible workaround is, in addition to calling `[self changeColor:[[UIApplication sharedApplication].delegate.window.subviews firstObject]];` in `setThemeVersion:`, also calling `[self changeColor:[UIApplication sharedApplication].delegate.window.rootViewController.view];` but it creates a warning because of the `DKNightVersionChangeColorProtocol`

**Comment by Draveness** [comment]
Yes, I tries this. And there is a problem with modal view controller. But I cannot fix it with 

```
[self changeColor:[UIApplication sharedApplication].delegate.window.rootViewController.view];
```

And I am working on it now.

**Comment by Draveness** [comment]
I will fix this problem tomorrow, this problem occurs when push or present.
