### ISSUE TITLE
still NoMethodError, bundle install already excuted

### ISSUE THREAD

**Issue by portwatcher** [Draveness/DKNightVersion#20]
![image](https://cloud.githubusercontent.com/assets/2919533/11163885/24a03c3a-8b1b-11e5-8683-65aa54aa207b.png)

It always broke at the Objective-C port of Google's `libPhoneNumber`

Anyway, the categories under UIKit folder have been generated fine.

**Comment by Draveness** [comment]
This is not the required step, you can just use this cocoapods to add this repo to your project.

**Comment by portwatcher** [comment]
But I need to customize a class to meet my requirements.
