### ISSUE TITLE
Crash on iOS8

### ISSUE THREAD

**Issue by ioswater** [Draveness/DKNightVersion#28]
Hi,Draveness
Your work great, like the sunshine. hah

At iPhone 6Plus, click cell and go into the detail view, then come back and change the neight mode, it will crash.

Wating for your message.

**Comment by Draveness** [comment]
Sorry, I follow the step you provide but it runs well

**Comment by ioswater** [comment]
Did you use iPhone 6 Plus?  It is also well done on my other device. And you can follow the step then change the mode more times. Because it show on my device every time。   Thanks a lot.

**Comment by Draveness** [comment]
Yep, I use iPhone 6 Plus but did not reproduce this bug

**Comment by ioswater** [comment]
Sorry about our ambiguous question. We test so many device , and finally, we found the demo will crash on the device of system version 8.4.

**Comment by Draveness** [comment]
I will fix this after downloading the iOS 8 simulator :dog:

**Comment by wenxp** [comment]
Hi,Draveness
 How to resolve it?

**Comment by Draveness** [comment]
temp fix in bd9ce59b3188bbae3f2a0dc2d1dff90397c44530

**Comment by Draveness** [comment]
Fixed in https://github.com/Draveness/DKNightVersion/pull/38
