### ISSUE TITLE
demo在iOS8进行切换页面后再次更改夜间模式会崩溃

### ISSUE THREAD

**Issue by xiao-xi** [Draveness/DKNightVersion#29]
进入应用，点击cell进入二级页面，然后pop回rootViewController，点击change，程序崩溃。
此现象在模拟器和真机都会发生，测试条件：iOS8.1，iOS8.4.
希望尽快解决

**Comment by Draveness** [comment]
same as #28

**Comment by Draveness** [comment]
same as #28
