### ISSUE TITLE
UIButton backgroumdImage support needed

### ISSUE THREAD

**Issue by xtcan** [Draveness/DKNightVersion#30]

**Comment by Draveness** [comment]
你可以自己写一个 DKColorPicker 只要返回 UIColor 就可以

**Comment by xtcan** [comment]
你好，不是很理解[enterBtn setBackgroundImage:[UIImage imageNamed:@"homepage_inbutton_on"] forState:UIControlStateHighlighted]; 那个图片参数怎么弄？分两个模式

**Comment by Draveness** [comment]
```objectivec
[btn dk_setBackgroundImage:^() { xxxx return image } forState:xx];
```

**Comment by Draveness** [comment]
DKNightVersion doesn't support multiple image switching for current version

**Comment by Draveness** [comment]
fixed
