### ISSUE TITLE
hey man , thanks your code. it's very helpful to me , and could you please add a borderColor to night version，thx very much

### ISSUE THREAD

**Issue by michaelmou** [Draveness/DKNightVersion#32]

**Comment by Draveness** [comment]
boarder color? Do you mean borderColor

**Comment by michaelmou** [comment]
yes

**Comment by Draveness** [comment]
added in 36870fc06e1bd59c854a4568ef07dc44a27a0c23, you could use this in the lastest version 1.1.0

**Comment by michaelmou** [comment]
thank you .

**Comment by Draveness** [comment]
And thx for your adivec

**Comment by michaelmou** [comment]
does it have a color name "NSForegroundColorAttributeName" in night version ??

**Comment by Draveness** [comment]
No not yet, I consider it is a little bit tricky to add this to this lib. But you could observe the notification and change the NSForegroundColorAttributeName there

**Comment by michaelmou** [comment]
i have done it before...
