### ISSUE TITLE
Crashed at [DKNightVersionManager setThemeVersion:]

### ISSUE THREAD

**Issue by portwatcher** [Draveness/DKNightVersion#33]
DKNightVersionManager.m line 57
-[DKNightVersionManager setThemeVersion:]

detail provided here:
http://crashes.to/s/13bfdbf85f3

We are using 0.9.3. If you fix this bug in the latest release, feel free to close it.

**Comment by Draveness** [comment]
I think this is already fixed in the latest version. And this lib changed a lot after 1.0.0 released

**Comment by portwatcher** [comment]
Because there are a lot of breaking changes, so we have to continue using 0.9.3...  T^T

**Comment by Draveness** [comment]
I feel sorry about that = =, and if you need some other help. Feel free to open another issue. =, =

**Comment by portwatcher** [comment]
It's OK.
Glad to see an open source project is being pushed forward bravely.

We will move to 1.x ASAP.
