### ISSUE TITLE
CALayer+Night 没测试吧， 里面的写错了 ，都是setBorderColor ..

### ISSUE THREAD

**Issue by dadadong** [Draveness/DKNightVersion#34]

**Comment by Draveness** [comment]
哪错了？可以指出来么，我看了下没找到错误，是测试过的，测试完了，代码删掉了，效果太丑了，可能是我回滚了一次？

**Comment by Draveness** [comment]
我靠，我知道了，我没提那个 commit thx

**Comment by Draveness** [comment]
fixed in 1.2

**Comment by dadadong** [comment]
哈哈~~ ，粗心了吧， 其实我还有个问题请教下， 我的app在打开过大量的页面后， 再切换夜间 or 白天 模式 ，主线程会卡住很久 ,最长卡到 10秒后，页面颜色才改变 ，请问这种情况我有没有办法来解决下 ，谢谢
