### ISSUE TITLE
When you remove observed control from NSNotificationCenter?

### ISSUE THREAD

**Issue by blackchena** [Draveness/DKNightVersion#37]
When you remove observed control from NSNotificationCenter?

**Comment by blackchena** [comment]
I see your header is Draveness,I'm a Draveness's follower ，I have play more than one thousand games with him。

**Comment by Draveness** [comment]
Sorry, I don't know the Draveness in your word. I used this ID for several years.

There is some problem with observer now. I'm planning to fix this is further release

**Comment by Draveness** [comment]
fixed in https://github.com/Draveness/DKNightVersion/pull/38
