### ISSUE TITLE
Support more themes wanted

### ISSUE THREAD

**Issue by SummertimSadness** [Draveness/DKNightVersion#39]
我仿照你的项目做了一个demo，可以支持更多的主题切换。我不会ruby，所以不知道怎么添加到你的项目里面。希望你能越做越好。
https://github.com/SummertimSadness/METhemeKit

**Comment by Draveness** [comment]
These features will not be added into this lib but thx for ur advice

**Comment by SummertimSadness** [comment]
why not?

**Comment by Draveness** [comment]
Just cuz i do not have time now
From Draveness
On 周三, 3月 9, 2016 at 09:57, SummertimSadness <notifications@github.com> wrote:
why not?

—
Reply to this email directly or view it on GitHub
[https://github.com/Draveness/DKNightVersion/issues/39#issuecomment-194064017] .[https://github.com/notifications/beacon/AGMUR1tmhQY-nkVHW-8ZjujN2ABArIdaks5prij6gaJpZM4HqmQE.gif]

**Comment by Draveness** [comment]
Supported In 2.0.0
