### ISSUE TITLE
Can't not support XIB

### ISSUE THREAD

**Issue by likid1412** [Draveness/DKNightVersion#4]
In Demo
1. create `TestTableViewCell` class, also create xib.
2. dray label and button, layout like `TableViewCell`, set the text color (Red or else) using xib
3. don't set textColor for `TestTableViewCell`, only set `nightTextColor`, like this

```
- (void)awakeFromNib {
    [DKNightVersionManager addClassToSet:self.class];
    
    self.label.numberOfLines = 0;
    self.label.text = @"DKNightVersion is a light wei-ght framework adding night   version to your iOS app.";
//    self.label.textColor = [UIColor darkGrayColor];
    self.label.lineBreakMode = NSLineBreakByCharWrapping;
    self.nightBackgroundColor = UIColorFromRGB(0x343434);
}
```

4. register this nib, and use it replace `TableViewCell`
5. run
6. switch night and day theme, then you will see label color can't change back to Red color.

I think this code cause the problem:

```
- (void)hook_setTextColor:(UIColor*)textColor {
    if ([DKNightVersionManager currentThemeVersion] == DKThemeVersionNormal) [self setNormalTextColor:textColor];
    [self hook_setTextColor:textColor];
}
```

May be UILabel don't call `setTextColor:` method, instead directyly using `_textColor = [UIColor xxxColor]`

**Comment by Draveness** [comment]
Hi, Thanks for your detailed response.

I have gave up using xib for a year. And nowadays, I didn't use xib in either of my projects. So I didn't consider of xib file.

I will try to fix it in next several days. And sorry for inconvenience. :)

**Comment by Running2snail** [comment]
这个报错是什么原因，？
夜间模式返回以后，单元格颜色以及一些label等空间的颜色变不回来怎么处理？

**Comment by Draveness** [comment]
Can you open a new issue for this repo? And please describe your problem in detail.

**Comment by Running2snail** [comment]
demo打开以后有四个报错， 在这个方法里面

- (void)testManagerUseDefaultThemeVersion {
    BOOL useDefaultThemeVersion = [DKNightVersionManager useDefaultNightColor];
    XCTAssertTrue(useDefaultThemeVersion, @"DKNightVersionManager use default theme version should be true");
    [DKNightVersionManager setUseDefaultNightColor:NO];
    useDefaultThemeVersion = [DKNightVersionManager useDefaultNightColor];
    XCTAssertFalse(useDefaultThemeVersion, @"After changing,  use default theme version should be false");
}



另外文件引入工程后，夜间模式返回后，一些单元格的颜色变不回来，怎么处理？
可以的话加我扣扣i496668219

**Comment by Draveness** [comment]
You should use the latest version. Default night color version is removed in the latest version.

**Comment by Running2snail** [comment]
怎么下载最新版本，是这个夜间模式最新版本？

**Comment by Draveness** [comment]
Yep.

**Comment by Running2snail** [comment]
How to download the latest version？

**Comment by Draveness** [comment]
U should use Cocoapod to integrate this library or git clone to download codes
here.

From Draveness
On 周日, 6月 14, 2015 at 19:23, Running2snail <notifications@github.com> wrote:
How to download the latest version？

—
Reply to this email directly or view it on GitHub
[https://github.com/Draveness/DKNightVersion/issues/4#issuecomment-111814804] .[https://github.com/notifications/beacon/AGMUR3nqRsa23uzd662DOLKF6vvXWf-bks5oTVuqgaJpZM4E1-qf.gif]

**Comment by Running2snail** [comment]
This link to open what all have no, sorry, could you please speak a little bit more detailed

**Comment by Draveness** [comment]
I think maybe you will see the download zip button on the right of the repo
homepage. And this is a github usage problem.

From Draveness
On 周日, 6月 14, 2015 at 19:41, Running2snail <notifications@github.com> wrote:
This link to open what all have no, sorry, could you please speak a little bit
more detailed

—
Reply to this email directly or view it on GitHub
[https://github.com/Draveness/DKNightVersion/issues/4#issuecomment-111815342] .[https://github.com/notifications/beacon/AGMUR8z16Haswm_PVhW6tXBklVB-FZqUks5oTV_LgaJpZM4E1-qf.gif]

**Comment by Running2snail** [comment]
When shown on the file download complains, No known class method for the selector "setUseDefaultNightColor" or "No known class method for the selector 'setUseDefaultNightColor:' In the above methods， if can use after delete DKNightVersionManagerTest file, if the number of rows into 20 lines, switching back and forth page there will be some cell color change don't come back  
This is because the version of the error?

**Comment by Running2snail** [comment]
If I need to add the UIKit control to set, and then remove elsewhere, or need to use some methods, complete normalColor and nightColor conversion between

**Comment by Running2snail** [comment]
If I need to add the UIKit control to set, and then remove elsewhere, or need to use some methods, complete normalColor and nightColor conversion between

**Comment by Draveness** [comment]
Why do you want to add to set and remove elsewhere. And I remove the setUseDefaultNightColor test in 0.8.1 because I forget to do that in the 0.8.0 version. But I donot know why, Remove it or not does no effect to my compling

**Comment by Running2snail** [comment]
Because after I set the night mode, there will be some color error chaos, some controls or cell can't back to the previous color, so I'm considering whether to save the normal color

**Comment by chrisballinger** [comment]
Does this still appear to be an issue? I am looking to integrate this and have a few XIB based table cells

**Comment by jyounus** [comment]
I've got the same question. Does this now work fine with XIB files? Can someone please confirm?

**Comment by Draveness** [comment]
This cannot work for XIB files

From Draveness
On 周日, 10月 11, 2015 at 01:51, Junaid Younus <notifications@github.com> wrote:
I've got the same question. Does this now work fine with XIB files? Can someone
please confirm?

—
Reply to this email directly or view it on GitHub
[https://github.com/Draveness/DKNightVersion/issues/4#issuecomment-147112497] .[https://github.com/notifications/beacon/AGMUR6N2xq3s8jktfIYSKSnTQKbzCc8Mks5o6UebgaJpZM4E1-qf.gif]

**Comment by smallqiang** [comment]
I use xib to create UILabel and UIButton.But the normal color will be changed when reload.The problem is solved?

**Comment by Draveness** [comment]
xib will not support by DKNightVersion
