### ISSUE TITLE
Increase Theme Dynamically

### ISSUE THREAD

**Issue by MickeyHub** [Draveness/DKNightVersion#44]
Hi, @Draveness , as title said, it's a bit difficult to increase theme dynamically in one file (ColorTable.txt), so I think it's better to refactor and abstract picker getter layer and storage layer.

## Limit: 
* all themes in one files.
* picker getter layer strongly couple with storage layer.

## Enhancement:
* abstract picker getter layer and storage layer.

## As A Result:
After refactor and abstract, we can save themes into respective file. and have custom picker getter from storage layer, which has been abstracted. if user can download theme, they only have to download one theme file, into sandbox, the directory structure maybe: 
```
Documents
└── Themes
    ├── Night.theme
    ├── Normal.theme
    └── Summer.theme
```

if you think it right, and no time to refactor, I'm glad to send PR :) .

**Comment by Draveness** [comment]
I think it is a great idea. But after we pod install DKNightVersion, this lib should be able to find the right folder which contain these theme file.

**Comment by MickeyHub** [comment]
so, one **Bold Hypothesis** :  no need for `*Picker`

## Reason
As user only use one theme at  the same time, so I think we not have to bind a ColorPicker or ImagePicker to a view. and even thought we save themes into respective file, when user download new theme, we have to add it's every color and image to every picker, which has been bound to views.

## Solution
we only need to know the theme currently user used, and bind only the color to a view. 
when user change theme, we only need to load new themes file to memory, view only need refresh self using a common getter method, this method will get color or image from the current theme, which has been loaded into memory as a structure, e.g, NSArray, NSDictionary.

## Effect
1.user change theme, the view get notification and refresh self, just these to-dos.

but, if this is the case,  it may be a rebuild for this project ?

**Comment by Draveness** [comment]
Thanks for your response. I really think about this for a while before. 

The biggest motive I made this lib is because I wanna to solve this problem in code, not in some setting file.That is why the first version of `DKNightVersion` providing a `nightXXColor`. 

I think picker is a balance between **color setting file** and **hard code**.

We can use some setting for common use, and sometimes need to create some temp picker:

```objective
self.button.dk_backgroundColorPicker = ^(DKThemeVersion *themeVersion) {
    if (themeVersion == DKThemeVersionNormal) {
        if (button.selected) {
             return xxxxx
        } else {
             return xxxxx
        }
    } else {
        return xxxxx
    }
};
```

**Comment by MickeyHub** [comment]
thanks, it's not your original intention, so I'll fork this repo if needed or create new one, thank you very much. :)

**Comment by Draveness** [comment]
:-)
