### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by vviicc** [Draveness/DKNightVersion#46]
看了下源代码，思路清晰，功能强大👍。有两个疑问：
1.代码收敛方面，现在还是需要在原来代码基础上添加setDk_backgroundColorPicker等方法，如果项目需要替换为另一个夜间模式库，那样的话重构成本会很大。有没有考虑在不破坏原有项目代码基础上实现，比如夜间模式配置文件？
2.有没有办法添加通用的夜间颜色属性，比如所有的UITableView的backgroundColor都共用一个颜色

**Comment by Draveness** [comment]
1. 对于切换 lib 的问题，暂时没有什么解决方案，也没有这方面你的计划
2. 对于第二个问题，也不是这个 repo 要解决的问题，你可以使用 method_swizzling 在 viewdidload 或者 tableview init 的时候设置其 picker 来达到这个效果
