### ISSUE TITLE
Example打开后无法运行，显示头文件无法找到。 

### ISSUE THREAD

**Issue by rydensun** [Draveness/DKNightVersion#47]
![image](https://cloud.githubusercontent.com/assets/10702116/15819918/8aaab1d8-2c18-11e6-9c16-dfd4eec209db.png)
/Users/user/Xcode projects/DKNightVersion/Example/Example/TableViewCell.m:10:9: 'DKNightVersion/DKNightVersion.h' file not found

**Comment by Draveness** [comment]
clone 这个仓库，并没有遇到这个问题

**Comment by rydensun** [comment]
Clone 了好几次，每次都是一打开就会出现这个问题。 

有任何可能的解决办法嘛？

**Comment by Draveness** [comment]
你的 Xcode 版本多少，你可以试下 build DKNightVersion 这个 target 再运行 Example

**Comment by rydensun** [comment]
看了下您的error显示是framework没有找到。 
error: /Users/apple/Library/Developer/Xcode/DerivedData/DKNightVersion-gzwybvmnrearmpfqbbgyixwiuuuu/Build/Products/Debug-iphoneos/DKNightVersion.framework: No such file or directory

DKNightVersion这个target可以成功build。 

我的Xcode是7.3.1
谢谢。

**Comment by Draveness** [comment]
你可以把 DKNightVersion.framework 框架加入到 Embedded Binaries 里面
Regards, Draveness
On Tue, Jun 7, 2016 at 10:12, rydensun <notifications@github.com> wrote:
看了下您的error显示是framework没有找到。
error: /Users/apple/Library/Developer/Xcode/DerivedData/DKNightVersion-gzwybvmnrearmpfqbbgyixwiuuuu/Build/Products/Debug-iphoneos/DKNightVersion.framework: No such file or directory

DKNightVersion这个target可以成功build。

我的Xcode是7.3.1
谢谢。

**Comment by rydensun** [comment]
你好，

我操作了Embedded Binaries里面的framework， 删掉了Example的，换成了DKNightVersion的。 在虚拟机上跑的通。 但是真机上会白屏，报错。 

dyld: Library not loaded: @rpath/DKNightVersion.framework/DKNightVersion
  Referenced from: /var/containers/Bundle/Application/71C7CE42-075B-4111-B482-5A3140D945D7/Example.app/Example
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/71C7CE42-075B-4111-B482-5A3140D945D7/Example.app/Frameworks/DKNightVersion.framework/DKNightVersion: mach-o, but wrong architecture

谢谢，
Ryden

**Comment by Draveness** [comment]
@BinBear 我 clone 了一下，没问题
