### ISSUE TITLE
会崩溃

### ISSUE THREAD

**Issue by full-of-fire** [Draveness/DKNightVersion#48]
![qq20160608-0](https://cloud.githubusercontent.com/assets/11729172/15879644/b8900530-2d58-11e6-8945-3280ca1e0938.png)

**Comment by Draveness** [comment]
请提供更详细的说明

**Comment by full-of-fire** [comment]
![qq20160608-1](https://cloud.githubusercontent.com/assets/11729172/15881008/1c3481fe-2d65-11e6-8f42-f1498e181695.png)
![qq20160608-2](https://cloud.githubusercontent.com/assets/11729172/15881007/1c2f1c82-2d65-11e6-8376-03145fe7b2ed.png)
我现在集成了你2.3.0版本到项目中，只要一运行就会崩溃，就是数组中添加nil的错。这怎么解决？以前可以，今天要上线，大神求解决啊！

**Comment by Draveness** [comment]
你是使用文件加载颜色的么，我想看一眼那个颜色配置文件

**Comment by Draveness** [comment]
这个方法是怎么被调用的，你穿进去了几个参数

**Comment by full-of-fire** [comment]
非常感谢你能及时的回复我
![qq20160608-3](https://cloud.githubusercontent.com/assets/11729172/15881935/c15aebc6-2d6c-11e6-9654-da5a79825f78.png)
![qq20160608-4](https://cloud.githubusercontent.com/assets/11729172/15881937/c616333c-2d6c-11e6-90b5-578a1ce00dfe.png)
我不是用文件加载的。就设置了两个主题，夜间模式和日间模式啊，

**Comment by Draveness** [comment]
你需要确保文件中只有两列颜色 NORMAL 和 NIGHT, 如果有别的列，请删除掉

Regards,
Draveness

**Comment by Draveness** [comment]
你发的那个图里 themes 有多少个

**Comment by full-of-fire** [comment]
![qq20160608-5](https://cloud.githubusercontent.com/assets/11729172/15882323/266d50aa-2d70-11e6-973b-910831b00a63.png)
这个默认你的文件哦，，，我xu'ya需要把后面的删除么 ？就两个主题

**Comment by full-of-fire** [comment]
而且我也没设置主题哦

**Comment by full-of-fire** [comment]
我删除了最后一个，现在不会崩溃了，谢谢你的耐心解决！！

**Comment by Draveness** [comment]
没事，有问题可以在这里留言，我把这个 issue 关了

**Comment by full-of-fire** [comment]
好的，谢谢！！
