### ISSUE TITLE
does DKNightVersion support CAlayer BackgroundColor?

### ISSUE THREAD

**Issue by yupliang** [Draveness/DKNightVersion#49]
does DKNightVersion support CAlayer BackgroundColor?  I use it set a background color for layer but it display another.

**Comment by Draveness** [comment]
Use property dk_backgroundColorPicker for CALayer

**Comment by yupliang** [comment]
I try to understand what you said 

> Use property dk_backgroundColorPicker for CALayer and pass UIColor as parameter
and use the code below , still it doesn't work. :(
`_backgroundlayer.dk_backgroundColorPicker = DKColorPickerWithColors(UIColorFromRGB(0xf8f7f5),UIColorFromRGB(0x333333));`

**Comment by Draveness** [comment]
just fixed, there is a typo in source code, thanks for your feedback

**Comment by yupliang** [comment]
so hope you update the cocoaPods version soon,thanks a lot.

**Comment by Draveness** [comment]
Will release version 2.3.1 in an hour
