### ISSUE TITLE
使用代码为 Xcode 工程添加文件 

### ISSUE THREAD

**Issue by ytx0574** [Draveness/DKNightVersion#5]
使用xcodeproj添加文件到项目中, 最后那段代码怎么使用的? 没有详细说明啊.  能否留个联系方式问问?

**Comment by Draveness** [comment]
什么意思, 我没有明白..

**Comment by ytx0574** [comment]
http://deltax.me/bei-xcodeproj-keng-de-zhe-ji-tian/?utm_source=tuicool 我看的你这篇文章.

之前没懂怎么调用的ruby代码, 现在我能在终端中执行这段代码. 但是怎么能使用object-c调用ruby并且传入参数到ruby代码中?  我需要把生成引用的目录从外部传入进去.

**Comment by ytx0574** [comment]
其实我就想问问怎么向.rb文件传入参数(里面是ruby代码)?  或者说Object-c怎么执行ruby代码?

**Comment by Draveness** [comment]
这跟这个框架没什么关系吧.

**Comment by ytx0574** [comment]
其实我第一次问的问题是怎么执行你博客里面的最后一段代码? 后面的都是衍生出来的问题. 不过还是感谢你的分享,学到了不少东西. 谢谢!

**Comment by Draveness** [comment]
怎么执行...你让我怎么说.. 我这是从这个框架里面提取的代码. 你问的也太笼统了, 你走到了哪一步, 哪里有问题?
