### ISSUE TITLE
关于使用DKNightVersion后自定义UIView无法释放的问题

### ISSUE THREAD

**Issue by Suninus** [Draveness/DKNightVersion#50]
我发现旧版本有这样的问题，新版本已经解决，想问一下你这块是怎么解决的。。。

**Comment by Draveness** [comment]
看看这里 https://github.com/Draveness/DKNightVersion/tree/master/DKNightVersion/DeallocBlockExecutor

**Comment by Suninus** [comment]
跟这个没关系，是你移除了
 __weak typeof(self) weakSelf;
        if ([[UIDevice currentDevice].systemVersion floatValue] < 9.0) {
            [[NSNotificationCenter defaultCenter] addObserverForName:DKNightVersionNightFallingNotification
                                                              object:nil
                                                               queue:nil
                                                          usingBlock:^(NSNotification * _Nonnull note) {
                                                              [weakSelf night_updateColor];
                                                          }];
            [[NSNotificationCenter defaultCenter] addObserverForName:DKNightVersionDawnComingNotification
                                                              object:nil
                                                               queue:nil
                                                          usingBlock:^(NSNotification * _Nonnull note) {
                                                              [weakSelf night_updateColor];
                                                          }];
        } else {
            [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(night_updateColor) name:DKNightVersionNightFallingNotification object:nil];
            [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(night_updateColor) name:DKNightVersionDawnComingNotification object:nil];
        }
旧版本没有 __weak typeof(self) weakSelf;这是我新加的。

**Comment by Draveness** [comment]
现在就是这么解决的 https://github.com/Draveness/DKNightVersion/tree/master/DKNightVersion/DeallocBlockExecutor

我不明比你啥意思
