### ISSUE TITLE
怎么设置webView的夜间模式

### ISSUE THREAD

**Issue by CYZZ** [Draveness/DKNightVersion#51]
在使用webView的时候如果使用普通的设置方式self.webView.dk_backgroundColorPicker = DKColorPickerWithKey(BAR);没有效果，应该如何设置呢？也就是说如何设置webView的背景颜色。

**Comment by mengerpiao** [comment]
webview内部要使用JS

**Comment by Draveness** [comment]
你可以监听 DKNightVersionThemeChangingNotificaiton 通知，在方法里面 reload js
