### ISSUE TITLE
Cocoa Pods重新pod install 后报错？

### ISSUE THREAD

**Issue by penguin-penpen** [Draveness/DKNightVersion#54]
之前可以正常编译运行，重新pod install后报错。
是版本更新的问题吗？按照readme的文档改了之后还是报错。

`    _backView.dk_backgroundColorPicker = DKColorWithColors(KCOLOR_YELLOW_FDF5D8, [UIColor colorWithRGBHex:0x343434]);`

> Implicit declaration of function 'DKColorWithColors' is invalid in C99

> Implicit conversion of 'int' to 'DKColorPicker' (aka 'UIColor *(^)(DKThemeVersion *__strong)') is disallowed with ARC

> Invalid block pointer conversion assigning to 'DKColorPicker' (aka 'UIColor *(^)(DKThemeVersion *__strong)') from 'int'

**Comment by Draveness** [comment]
现在版本是最新的么

**Comment by Draveness** [comment]
你把全局的 `DKColorWithColors` 改成 `DKColorPickerWithColors`，这里多加了一个 Picker 是为了保证语义上不会出问题

**Comment by penguin-penpen** [comment]
谢谢，不报错了。不过我今天看到已经升级到`2.3.1`了，但pod install安装的还是`2.3.0`版本的。

**Comment by Draveness** [comment]
你需要更新本地的 repo 了，不过影响也不是很大

Regards,
Draveness
