### ISSUE TITLE
[__NSMallocBlock__ set]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by xiangyaguo** [Draveness/DKNightVersion#58]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSMallocBlock__ set]: unrecognized selector sent to instance 0x14eaa5ba0

你好，在运行的时候回出现这个错误，不是必现的，偶尔会出现这个崩溃。

**Comment by Draveness** [comment]
最好能够给一个上下文，要不然很难做，调用栈有么，如果有的话麻烦发一下

**Comment by xiangyaguo** [comment]
我的写法问题。
`NSForegroundColorAttributeName : DKColorPickerWithKey(TEXT999)`
把picker当做color了。
