### ISSUE TITLE
改变不同日间和夜间模式的文字

### ISSUE THREAD

**Issue by CYZZ** [Draveness/DKNightVersion#59]
在可以修改日间和夜间模式的图片，如何动态修改日间和夜间模式下按钮显示不同文字呢？好像通知可以实现，但是控件需要改成成员变量，不同通知有没有和imageView一样可以设置两种状态下的显示文字呢？

**Comment by Draveness** [comment]
没有，还是用通知吧，之后可能会加个 block 方法，在主题改变时，执行 block，不过不一定
