### ISSUE TITLE
Test testManagerUseDefaultThemeVersion is broken

### ISSUE THREAD

**Issue by romanvbabenko** [Draveness/DKNightVersion#6]
/DKNightVersion/DKNightVersionTests/DKNightVersionManagerTest.m:33:36: Use of undeclared identifier 'DKNightVersion'

/DKNightVersion/DKNightVersionTests/DKNightVersionManagerTest.m:35:28: No known class method for selector 'setUseDefaultNightColor:'

/DKNightVersion/DKNightVersionTests/DKNightVersionManagerTest.m:36:53: No known class method for selector 'useDefaultNightColor'

xcode 6.3, iOS 8.3

**Comment by Draveness** [comment]
In the latest version for DKNightVersion. I have already remove `useDefaultNightColor` behavior. Because this may cuz unpredictable behavior to UIKit components.

**Comment by romanvbabenko** [comment]
Yes, normally you're removed some functions, but you should fix tests after that, isn't? Right now your tests are broken, that's what I'm telling you.

**Comment by Draveness** [comment]
Already fix this
