### ISSUE TITLE
crash on iOS 7.0

### ISSUE THREAD

**Issue by xiangyaguo** [Draveness/DKNightVersion#60]
- [UISearchBar setKeyboardAppearance:]: unrecognized selector sent to instance，崩溃在UISearchBar+Keyboard的dk_init方法里面。

**Comment by Draveness** [comment]
我回去看一下

**Comment by Draveness** [comment]
UISearchBar 不支持 setKeyboardAppearance 么？

**Comment by xiangyaguo** [comment]
API 是支持的，但是实际跑起来报错了

**Comment by Draveness** [comment]
有堆栈信息么

**Comment by xiangyaguo** [comment]
-[UISearchBar setKeyboardAppearance:]: unrecognized selector sent to instance 0x100b3bf50
(null)
((
	0   CoreFoundation                      0x00000001829130b8 <redacted> + 160
	1   libobjc.A.dylib                     0x000000018e891d78 objc_exception_throw + 60
	2   CoreFoundation                      0x0000000182917d14 <redacted> + 0
	3   CoreFoundation                      0x0000000182915a7c <redacted> + 912
	4   CoreFoundation                      0x00000001828354ac _CF_forwarding_prep_0 + 92
	5   myAppName                           0x100359e90 myAppName + 3514000
	6   myAppName                           0x1000aa6d8 myAppName + 698072
	7   myAppName                           0x10009d8ac myAppName + 645292
	8   UIKit                               0x00000001857e82c0 <redacted> + 576
	9   UIKit                               0x00000001858a17d0 <redacted> + 64
	10  UIKit                               0x00000001858a16cc <redacted> + 248
	11  UIKit                               0x00000001858a0ba0 <redacted> + 112
	12  UIKit                               0x00000001858a0840 <redacted> + 636
	13  UIKit                               0x00000001858a0564 <redacted> + 56
	14  UIKit                               0x00000001858a04e4 <redacted> + 200
	15  UIKit                               0x00000001857e2d78 <redacted> + 348
	16  QuartzCore                          0x00000001853df0cc <redacted> + 184
	17  QuartzCore                          0x00000001853d9c94 <redacted> + 300
	18  QuartzCore                          0x00000001853d9b4c <redacted> + 32
	19  QuartzCore                          0x00000001853d93d4 <redacted> + 280
	20  QuartzCore                          0x00000001853d9178 <redacted> + 424
	21  UIKit                               0x000000018586e1c8 <redacted> + 56
	22  UIKit                               0x0000000185856dd8 <redacted> + 1852
	23  UIKit                               0x00000001857e9530 <redacted> + 3336
	24  UIKit                               0x00000001857e8720 <redacted> + 104
	25  UIKit                               0x00000001858560b0 <redacted> + 712
	26  GraphicsServices                    0x0000000188239128 <redacted> + 676
	27  GraphicsServices                    0x0000000188238c54 <redacted> + 48
	28  CoreFoundation                      0x00000001828d2fc8 <redacted> + 56
	29  CoreFoundation                      0x00000001828d2f28 <redacted> + 444
	30  CoreFoundation                      0x00000001828d114c <redacted> + 1620
	31  CoreFoundation                      0x0000000182811b38 CFRunLoopRunSpecific + 452
	32  UIKit                               0x00000001858552d4 <redacted> + 784
	33  UIKit                               0x00000001858500e8 UIApplicationMain + 1156
	34  myAppName                           0x1000f6328 myAppName + 1008424
	35  libdyld.dylib                       0x000000018ee7baa0 <redacted> + 4
)

**Comment by xiangyaguo** [comment]
https://developer.apple.com/library/ios/releasenotes/General/iOS70APIDiffs/index.html#//apple_ref/doc/uid/TP40013203 里面贴了 6.1 到 7.0 增加的api，searchbar 没有setKeyboardAppearance:这个方法，应该是UIKit里面标错了。

**Comment by Draveness** [comment]
👍
