### ISSUE TITLE
设置图片的时候出现诡异问题

### ISSUE THREAD

**Issue by Abitofcomedy** [Draveness/DKNightVersion#62]
使用DKImagePickerWithNames()时崩溃在这一步：
NSString *name = va_arg(names_list, NSString *);

项目中多处使用DKImagePickerWithNames()，有的地方崩溃，有的地方又没崩溃

崩溃都出现在真机测试的时候，模拟器则没有问题，IOS10系统

请问有什么解决办法吗？望赐教

**Comment by Draveness** [comment]
我现在不是 iOS 10，没有办法测试

**Comment by xiangyaguo** [comment]
可能是根据图片名未找到相应的图片传了一个nil导致崩溃。
