### ISSUE TITLE
DKColorPickerWithColors(<#UIColor *normalColor, ...#>)设置颜色问题

### ISSUE THREAD

**Issue by XHQFighting** [Draveness/DKNightVersion#63]
Xcode8 
 用DKColorPickerWithColors(<#UIColor *normalColor, ...#>)设置颜色，会在  
  for (NSUInteger i = 0; i < num_args; i++) {
        UIColor *color = va_arg(colors_list, UIColor *);
        [colors addObject:color];
    }
中的第二句UIColor *color = va_arg(colors_list, UIColor *)出现EXC_BAD_ACCESS崩溃
版本是 2.4.0

**Comment by Draveness** [comment]
能看一下具体调用的方法和颜色配置文件么
