### ISSUE TITLE
xcode8 ios10,出现崩溃  

### ISSUE THREAD

**Issue by WXinYi** [Draveness/DKNightVersion#64]
xcode8 ios10,出现崩溃  

> DKColorTable:
NORMAL   NIGHT   
#ffffff       #3f3f3f  BBG
#333333  #b3b3b3  TXTONE
#333333  #b3b3b3  TXTTWO
#666666  #949494  TXTTHREE
#999999  #949494  TXTFOUR
#f5f5f5     #4d4d4d  BG
#e0e1e2    #646464 SEP
#dedede   #727272  MYBOOK
#d38d8c   #ba1c18  SETTING

崩溃信息： *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: themes.count == colors.count'

我的qq：595357716

**Comment by Mrhyuan** [comment]
我也遇到了

**Comment by Draveness** [comment]
我下载了之后，跑了下没有问题，应该是你们使用的不对，最好提供更详细的信息，这样我没法解决

**Comment by WXinYi** [comment]
我解决问题了，谢谢了   DKColorTable.txt 之后不能有空格，有空格就会崩溃，具体什么原因也不大了解，只是我把  DKColorTable.txt文件内后面的空格和换行去掉后就好了，  可以提醒其他人，同时也感谢作者分享

**Comment by Draveness** [comment]
额。。。这个可能确实是一个 bug，我可以改一下

**Comment by Draveness** [comment]
在 2.4.1 中解决了

**Comment by fengong** [comment]
我也一直有个痛点，想把DKColorTable.txt更换为xml或者json，这样解析更通用，添加注释也更加方便

**Comment by Draveness** [comment]
@fengong #65

**Comment by sdqdChen** [comment]
我也遇到了，直接拖进去用的时候没报错，改了txt里面的一个值就报错了

**Comment by sdqdChen** [comment]
@Draveness
