### ISSUE TITLE
Do you have swift demo？

### ISSUE THREAD

**Issue by jasonji84** [Draveness/DKNightVersion#67]
It is quite strange that I can not use the current version for my swift3 project. I follow the instructions (pod install，#import <DKNightVersion/DKNightVersion.h> in header file). When I use DKColorPickerWithRGB, the compiler reports Use of unresolved identifier 'DKColorPickerWithRGB'.

I use DKNightVersion in swift2 and have no such problem. Besides, other obj-c libs are OK in use. 

Any suggestions? Thank you very much.

**Comment by Draveness** [comment]
Swift 3.0 doesn't support variadic functions
