### ISSUE TITLE
没有做nil判断

### ISSUE THREAD

**Issue by JRJian** [Draveness/DKNightVersion#73]
NORMAL   NIGHT    RED
#ffffff  #343434  #fafafa BG
#aaaaaa  #313131  #aaaaaa SEP
#0000ff  #ffffff  #fa0000 TINT
#000000  #ffffff  #000000 TEXT
#ffffff  #444444  #ffffff BAR
#f0f0f0  #222222  #dedede HIGHLIGHTED
#ffffff  #565656  #565656 TAGBG

文本无论怎么读，最后都有个换行符('\n')
导致数组最后一串字符读出来是空
NSString *key = [self keyFromEntry:entry];

**Comment by Draveness** [comment]
你用的是最新版么，没有问题

**Comment by JRJian** [comment]
pod install 默认是2.4.0。
后面我指定pod 2.4.2就没问题了。
thks
