### ISSUE TITLE
UIImageView添加alpha

### ISSUE THREAD

**Issue by HistoryZhang** [Draveness/DKNightVersion#74]
本想 pull requests的，但是发现UIKit部分都是模板生成的，所以就尴尬了。夜间模式时，希望给UIImageView的alpha值改小一点，不然有点刺眼。
所以加了一个这个：

```
@property (nonatomic, copy, setter = dk_setAlphaPicker:) DKAlphaPicker dk_alphaPicker;
```

然后有个
```
typedef CGFloat (^DKAlphaPicker)(DKThemeVersion *themeVersion);

DKAlphaPicker DKAlphaPickerWithAlphas(CGFloat normal, ...);

@interface DKAlpha : NSObject
+ (DKAlphaPicker)alphaPickerWithAlpha:(CGFloat)alpha;
@end
```

**Comment by Draveness** [comment]
这个东西搞成全局的怎么样

**Comment by HistoryZhang** [comment]
不建议这样，万一有些图片区分日夜间模式的，然后又应用了alpha，会怪怪的。可不可以再给UIView添加一个分类，然后手动处理？代码有点丑了…

**Comment by Draveness** [comment]
你其实可以提一个 PR，虽然是模板生成的，不过现在基本不会改了，改的话这一个文件手动改也是可以接受的

**Comment by HistoryZhang** [comment]
提了 PR， 不过好像出错了。

![qq20161212-1](https://cloud.githubusercontent.com/assets/4057123/21091347/93206bf8-c080-11e6-888d-0fd37e88e232.png)

**Comment by Draveness** [comment]
close by #75
