### ISSUE TITLE
DKColorTable.txt中添加UI配色的时候，运行后崩溃

### ISSUE THREAD

**Issue by LeoTaiMing** [Draveness/DKNightVersion#84]
DKColorTable.txt中添加UI配色的时候，运行后崩溃。我之前使用是没问题的。但是最近我添加颜色，突然就崩溃了。而且，我试了很久之前的项目。我添加颜色之后也出现了这个问题。实在找不到原因了...

**Comment by Draveness** [comment]
版本号多少

**Comment by LeoTaiMing** [comment]
最新版本。问题已经解决了，原因是在读取DKColorTable.txt中的数据的时候，莫名其妙的取出来一段空格（而我没有写空格），我加上了空数据判断，和空数据剔除就没问题了。
