### ISSUE TITLE
swift的调用问题

### ISSUE THREAD

**Issue by zhangfurun** [Draveness/DKNightVersion#91]
请问,如何解决swift中调用设置某view的正常和夜间模式的颜色,需求如下
正常 clear
夜间 black, alpha = 0.25
请问该如何设置
找到DKColorPickerWithColors,但是swift没办法调用
求指导

**Comment by Draveness** [comment]
swift 用这个吧 https://github.com/Draveness/NightNight

**Comment by zhangfurun** [comment]
谢谢,昨天看到了
